name: Warpstarvalcity
version: '${project.version}'
main: ch.tom.tcodes.WarpSystem
authors: [ T0myyde ]
description: Was a warp system for the server 𝗦𝗧𝗔𝗥𝗩𝗔𝗟𝗖𝗜𝗧𝗬

commands:
  delwarp:
    description: "Is used to delete a warp"
  setwarp:
    description: "Is responsible for creating a warp"
  warp:
    description: "Is responsible for the TP'n"
  warps:
    description: "Is for displaying all warps"
